### PR TITLE
Add ascii and general text functionality

### PR DESCRIPTION
**Pull request by magnetrwn**
Modified and added some code to provide easier printing of text, automated warnings in the demo as well as some animation.

### CODE REVIEW

**Comment by nopnop2002** [comment]
It's New Year's holiday in Japan.
I'll check it out after the holidays are over.

**Comment by magnetrwn** [comment]
Sure, happy holidays!

**Comment by magnetrwn** [comment]
Expanded the module a bit, do you want to merge?
I added a GIF of the module working to the README if necessary.

**Comment by nopnop2002** [comment]
I got this error on Raspbian GNU/Linux 10 (buster):

```
Traceback (most recent call last):
  File "./tm1637.py", line 286, in <module>
    _demo(TM1)
  File "./tm1637.py", line 263, in _demo
    show_ip_address(tm)
  File "./tm1637.py", line 172, in show_ip_address
    shell=False
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/hostname': '/usr/bin/hostname'
```

```
Traceback (most recent call last):
  File "./tm1637.py", line 286, in <module>
    _demo(TM1)
  File "./tm1637.py", line 269, in _demo
    show_on_high_cpu_thermal(tm, 50, "/sys/devices/virtual/thermal/thermal_zone0/temp")
  File "./tm1637.py", line 232, in show_on_high_cpu_thermal
    shell=False
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/cat': '/usr/bin/cat'
```


```
Traceback (most recent call last):
  File "./tm1637.py", line 286, in <module>
    _demo(TM1)
  File "./tm1637.py", line 272, in _demo
    show_on_full_storage(tm, 85)
  File "./tm1637.py", line 215, in show_on_full_storage
    shell=False
  File "/usr/lib/python3.7/subprocess.py", line 395, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/bin/df': '/usr/bin/df'
```

```
$ which hostname
/bin/hostname
$ which cat
/bin/cat
$ which df
/bin/df
```

**Comment by magnetrwn** [comment]
I think `/usr/bin` is not present in your PATH, you should try:
```
$ export PATH="/usr/bin:$PATH"
$ which hostname
/usr/bin/hostname
```
Or another alternative would be to replace `/usr/bin` with `/bin` in the code, although `/usr/bin` is preferable :)

**Comment by nopnop2002** [comment]
```
$ ls /usr/bin/hostname
ls: cannot access '/usr/bin/hostname': No such file or directory
```

**Comment by magnetrwn** [comment]
Ok, now it should work on different distributions :)

**Comment by nopnop2002** [comment]
it worked correctly.

>I added a GIF of the module working to the README if necessary.

Yes. I want it.

**Pull request merged**
